# Generated by Django 5.0.4 on 2024-05-01 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_rename_path_file_file_alter_task_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='initiator',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
